### ISSUE TITLE
Is Tableau detection and restrictions

### ISSUE THREAD

**Issue by Jaxolotl** [datadotworld/tableau-connector#31]
@see https://github.com/datadotworld/tableau-connector/blob/master/src/App.js#L57

```
this.isTableau = navigator.userAgent.toLowerCase().indexOf('tableau') >= 0 || this.parsedQueryString.forceTableau
```

Hi there, I have 2 suggestions here:

## 1 detection
Using the user agent for detecting "isTableau" could be a source of problems in case the user agent change. Unfortunately we don't have an exposed method on the shim to detect that, but, I can show you how we do it on the shim

https://github.com/tableau/wdclib/blob/master/tableauwdc.js#L34

As you can see @ line 37, Tableau expose a global variable that you can use to determinate if the connector is running on Tableau Server/Desktop.
Using the `window.tableauVersionBootstrap` as we do you can rely on our implementation and this mechanism is less likely to be changed, anyway you can verify that file whenever you want (it's public) and follow any change.

## 2 restriction ( this is just a feedback from our experience )
I can see at
https://github.com/datadotworld/tableau-connector/blob/master/src/App.js#L60
and
https://github.com/datadotworld/tableau-connector/blob/master/src/App.js#L154

you're defining business logic ( in this case restrictions ) based on that detection. Even if at line 34 you could set `forceTableau` via querystring, we've found restrictions based on "isTableau" to be "not very useful", one of the most used tools for connectors dev/debug is the simulator, and adding a value to the querystring could be error/headache pron ( imagine a case were you need to take that param in consideration for an authentication proxy or for oauth redirections )
In our connectors, we only care if there's the shim or not, and simply fail if we don't have the vars exposed by Tableau. Furthermore, the connector might be running on our servers or on-prem ( customer's servers ) and the user agent won't be controlled by us, and more again, the user might want to use our keyring to store credentials in order to run server refreshes, and again, the user agent will be determined by the user's browser of choice.

**Comment by kndungu** [comment]
@Jaxolotl thanks for taking the time to give us such comprehensive feedback!


**1. Detection**

> and simply fail if we don't have the vars exposed by Tableau

Agreed, this is a more robust way of carrying out the detection. I'll update the code to use `window.tableauVersionBootstrap`

**2. Restriction**

*Some background:*

Users add data.world datasets to Tableau by getting a URL on data.world and pasting it on the tableau WDC pop up.

Since it's a URL they could be tempted to try and access it through a browser in which case we display instructions on how to use the URL on Tableau. Hence the need for `isTableau`, to detect when the app is accessed from a non-Tableau environment.

> one of the most used tools for connectors dev/debug is the simulator

This is what necessitates `|| this.parsedQueryString.forceTableau`

Since we would like the instructions to always be displayed when the app is accessed from a browser, adding `forceTableau` to the query string gives the developer a way of debugging the app from a browser.

This is really just a workaround meant to be used by those developing the app. `isTableau` will always be defined when running on Tableau (especially after the change to `window.tableauVersionBootstrap`).

It's not the most elegant way of doing it and any suggestions or recommendations are welcome.
